import type { Metadata } from "next";
import { BulletList, VisynContactBlock, VisynLegalActions, VisynLegalHero, visynDetails } from "../content";

export const metadata: Metadata = {
  title: "Visyn Terms of Service",
  description: "Terms of Service for Visyn, the CRM and business messaging platform by TEAM-PSMPV.",
  alternates: { canonical: "/products/visyn/terms" },
};

export default function VisynTermsPage() {
  return (
    <main id="main-content">
      <VisynLegalHero label="VISYN / TERMS" title="VISYN TERMS OF SERVICE" lead={`Last updated: ${visynDetails.updated}. Terms governing access to and use of Visyn.`} />
      <article className="content legal-document">
        <p><strong>Last updated: {visynDetails.updated}</strong></p>
        <p>These Terms of Service (“Terms”) govern access to and use of Visyn, provided by {visynDetails.legalEntity} (“TEAM-PSMPV”, “we”, “us”, or “our”).</p><p>By creating an account or using Visyn, you agree to these Terms.</p>
        <section><h2>1. Visyn service</h2><p>Visyn is a business software platform that may provide:</p><BulletList items={["Customer relationship management.", "Shared conversation inboxes.", "WhatsApp Business Platform integration.", "Contact and consent management.", "Message templates.", "Workflow automation.", "Campaign management.", "Reporting and operational tools.", "Optional AI-assisted features."]} /><p>Features may vary by plan, region, provider availability, and account status.</p></section>
        <section><h2>2. Eligibility and accounts</h2><p>You must:</p><BulletList items={["Be legally capable of entering into these Terms.", "Provide accurate account information.", "Keep your credentials secure.", "Ensure that people using your workspace are authorized.", "Notify us promptly of unauthorized access."]} /><p>You are responsible for activity performed through your account.</p></section>
        <section><h2>3. Business customer responsibilities</h2><p>You are responsible for:</p><BulletList items={["The accuracy and legality of your customer data.", "Obtaining required consent and permissions.", "Providing required privacy notices.", "Honoring opt-outs and suppression requests.", "Using approved WhatsApp templates where required.", "Ensuring messages are lawful, accurate, and appropriate.", "Complying with applicable privacy, consumer-protection, advertising, healthcare, financial, telecommunications, and anti-spam laws.", "Maintaining the necessary rights to use uploaded content and media."]} /><p>You must not use Visyn to send unlawful, deceptive, abusive, threatening, discriminatory, fraudulent, or unsolicited communications.</p></section>
        <section><h2>4. WhatsApp and third-party services</h2><p>WhatsApp, Meta, Cloud API, payment providers, and other integrations are third-party services.</p><p>Your use of those services is subject to their own terms, policies, technical restrictions, pricing, messaging limits, and approval decisions.</p><p>Meta may reject templates, limit messaging, suspend assets, or discontinue access. TEAM-PSMPV does not guarantee that Meta will approve a business, phone number, template, or message.</p></section>
        <section><h2>5. Coexistence</h2><p>Where supported and approved by Meta, Coexistence may allow a WhatsApp Business App number to be used with WhatsApp Business Platform.</p><p>Coexistence availability depends on Meta eligibility and configuration. TEAM-PSMPV does not guarantee that every number or business will qualify.</p></section>
        <section><h2>6. Fees</h2><p>Fees, taxes, subscription charges, usage charges, provider charges, and WhatsApp/Meta charges will be described in the applicable order, plan, or billing page.</p><p>Third-party messaging fees may change independently of TEAM-PSMPV pricing.</p></section>
        <section><h2>7. AI features</h2><p>AI features may generate classifications, summaries, recommendations, or draft responses.</p><p>AI output may be inaccurate or incomplete. You are responsible for reviewing AI output before relying on it or sending it externally unless a separately documented automation has been enabled by an authorized user.</p><p>AI must not be used as a substitute for professional medical, legal, financial, or other regulated advice.</p></section>
        <section><h2>8. Customer data</h2><p>You retain ownership of data submitted to Visyn.</p><p>You grant TEAM-PSMPV a limited right to host, process, transmit, and display that data solely to provide, secure, support, and improve the service as permitted by the applicable agreement and Privacy Policy.</p><p>You authorize TEAM-PSMPV to process data as necessary to operate integrations selected by you.</p></section>
        <section><h2>9. Prohibited use</h2><p>You must not:</p><BulletList items={["Reverse engineer or interfere with Visyn.", "Circumvent security or access controls.", "Upload malware.", "Use Visyn to violate law or third-party rights.", "Send spam or prohibited WhatsApp content.", "Attempt unauthorized access to another workspace.", "Use Visyn to make high-risk decisions without appropriate human review.", "Resell or sublicense Visyn unless expressly authorized."]} /></section>
        <section><h2>10. Availability and support</h2><p>We aim to provide reliable service but do not guarantee uninterrupted or error-free operation.</p><p>Service availability may be affected by Meta, WhatsApp, Cloudflare, internet providers, maintenance, outages, rate limits, or events outside our control.</p><p>Support is available at:</p><p><a href={`mailto:${visynDetails.email}`}>{visynDetails.email}</a><br /><a href={visynDetails.supportUrl}>Visyn support portal</a><br />{visynDetails.supportHours}</p></section>
        <section><h2>11. Suspension</h2><p>We may restrict or suspend access when reasonably necessary to:</p><BulletList items={["Protect the service.", "Prevent abuse or security harm.", "Comply with law.", "Respond to a provider restriction.", "Address unpaid fees.", "Investigate a violation of these Terms."]} /><p>Where practical, we will provide notice and an opportunity to resolve the issue.</p></section>
        <section><h2>12. Termination</h2><p>You may stop using Visyn at any time.</p><p>We may terminate an account for material breach, legal requirement, security risk, prolonged inactivity, or discontinuation of the service.</p><p>After termination, data will be handled according to the applicable retention and deletion process.</p></section>
        <section><h2>13. Intellectual property</h2><p>Visyn, its software, design, trademarks, documentation, and underlying technology belong to TEAM-PSMPV or its licensors.</p><p>These Terms do not transfer ownership of Visyn to you.</p></section>
        <section><h2>14. Disclaimers</h2><p>Visyn is provided on an “as available” and “as is” basis to the extent permitted by law.</p><p>We do not guarantee:</p><BulletList items={["WhatsApp or Meta approval.", "Message delivery.", "Template approval.", "Business verification.", "Coexistence availability.", "Specific business results.", "Continuous availability of third-party integrations."]} /></section>
        <section><h2>15. Limitation of liability</h2><p>To the maximum extent permitted by law, TEAM-PSMPV will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or loss of profits, revenue, goodwill, data, or business opportunity.</p><p>Our total liability will be limited to the fees paid by you for Visyn during the twelve (12) months before the event giving rise to the claim, except where applicable law does not allow that limitation.</p></section>
        <section><h2>16. Governing law</h2><p>These Terms are governed by the laws of Uttar Pradesh, India, without regard to conflict-of-law principles.</p><p>Courts located in Moradabad, Uttar Pradesh, India will have authority over disputes, subject to any mandatory rights under applicable law.</p></section>
        <section><h2>17. Changes</h2><p>We may update these Terms by publishing a new version and changing the “Last updated” date.</p></section>
        <section><h2>18. Contact</h2><VisynContactBlock /></section>
        <VisynLegalActions />
      </article>
    </main>
  );
}
