import type { Metadata } from "next";
import { BulletList, VisynContactBlock, VisynLegalActions, VisynLegalHero, visynDetails } from "../content";

export const metadata: Metadata = {
  title: "Visyn Privacy Policy",
  description: "Privacy Policy for Visyn, the CRM and business messaging platform by TEAM-PSMPV.",
  alternates: { canonical: "/products/visyn/privacy-policy" },
};

export default function VisynPrivacyPolicyPage() {
  return (
    <main id="main-content">
      <VisynLegalHero
        label="VISYN / PRIVACY POLICY"
        title="VISYN PRIVACY POLICY"
        lead={`Last updated: ${visynDetails.updated}. How TEAM-PSMPV collects, uses, stores and protects information when you use Visyn.`}
      />
      <article className="content legal-document">
        <p><strong>Last updated: {visynDetails.updated}</strong></p>
        <p>This Privacy Policy explains how {visynDetails.legalEntity} (“TEAM-PSMPV”, “we”, “us”, or “our”) collects, uses, stores, and protects information when you use Visyn, our customer relationship management and business messaging platform.</p>
        <p>Visyn helps businesses manage customer conversations, contacts, WhatsApp communications, workflows, automation, and related business operations.</p>

        <section><h2>1. Who we are</h2><p><strong>Data controller/business:</strong><br />{visynDetails.legalEntity}<br />{visynDetails.address}<br />{visynDetails.country}<br />Email: <a href={`mailto:${visynDetails.email}`}>{visynDetails.email}</a><br />Support: <a href={`mailto:${visynDetails.email}`}>{visynDetails.email}</a></p><p>For customers using Visyn to communicate with their own customers, the Visyn customer may determine the purposes of processing customer information. In those cases, Visyn processes information on behalf of that customer as a service provider or data processor, subject to our agreement with that customer.</p></section>
        <section><h2>2. Information we collect</h2><p>We may collect:</p><BulletList items={["Account information such as name, email address, phone number, password credentials, organization name, and role.", "Business information such as workspace details, billing information, configuration, and team membership.", "WhatsApp-related information such as WhatsApp Business Account IDs, phone number IDs, display names, message content, message status, timestamps, contact identifiers, media references, templates, and webhook events.", "CRM information entered by a Visyn customer, such as contact names, phone numbers, tags, notes, appointments, consent records, and custom fields.", "Technical information such as IP address, browser type, device information, log data, approximate location, authentication events, and security events.", "Support information when you contact us.", "Integration information from services that a customer chooses to connect to Visyn."]} /><p>We do not request or intentionally collect passwords for WhatsApp, Facebook, Meta Business Manager, or any other third-party account. Authentication is performed through the relevant third-party service.</p></section>
        <section><h2>3. How we use information</h2><p>We use information to:</p><BulletList items={["Provide, maintain, and secure Visyn.", "Connect and manage authorized WhatsApp Business Platform integrations.", "Receive and display inbound customer messages.", "Send authorized messages through WhatsApp Cloud API.", "Synchronize message delivery and read statuses.", "Manage contacts, conversations, templates, automations, campaigns, and assignments.", "Enforce consent, opt-out, messaging-window, and other policy controls.", "Authenticate users and administer workspaces.", "Prevent fraud, abuse, unauthorized access, and security incidents.", "Provide customer support.", "Monitor reliability, performance, and errors.", "Comply with legal obligations.", "Improve Visyn using aggregated or de-identified information where permitted."]} /><p>We do not sell personal information.</p></section>
        <section><h2>4. WhatsApp and Meta integrations</h2><p>When a business connects WhatsApp to Visyn, Visyn accesses only the WhatsApp Business assets and permissions authorized through Meta’s onboarding process.</p><p>The connected business controls its WhatsApp Business Account and may disconnect the integration through Visyn, Meta Business settings, or applicable WhatsApp controls.</p><p>WhatsApp and Meta process information under their own terms and policies. Their services may process message content, phone numbers, metadata, and delivery information according to their policies.</p><p>Visyn does not use WhatsApp customer information for unrelated advertising purposes.</p></section>
        <section><h2>5. Legal bases</h2><p>Where applicable, we process personal information because:</p><BulletList items={["It is necessary to provide the requested service.", "The business customer has instructed us to process it.", "We have a legitimate interest in securing and operating Visyn.", "We have obtained consent.", "Processing is necessary to comply with law."]} /><p>Businesses using Visyn are responsible for obtaining any consent, notice, authorization, or other legal basis required for their communications.</p></section>
        <section><h2>6. Sharing information</h2><p>We may share information with:</p><BulletList items={["Meta and WhatsApp when required to provide the WhatsApp integration.", "Cloud hosting, database, queue, security, analytics, email, support, and infrastructure providers.", "Professional advisers and auditors where necessary.", "Government authorities or law enforcement where legally required.", "A successor entity in connection with a merger, acquisition, financing, or sale of assets."]} /><p>Service providers may process information only for authorized business purposes and subject to appropriate contractual safeguards.</p></section>
        <section><h2>7. Retention</h2><p>We retain information only for as long as necessary to provide Visyn, meet contractual obligations, resolve disputes, maintain security, comply with law, and enforce agreements.</p><p>Retention periods may vary by:</p><BulletList items={["Account and billing records.", "Message and conversation records.", "CRM data.", "Audit and security logs.", "Backup data.", "Legal or regulatory requirements."]} /><p>Customers may request deletion of their workspace information as described in our <a href="/products/visyn/data-deletion">Data Deletion page</a> and customer agreement.</p></section>
        <section><h2>8. Security</h2><p>We use reasonable technical and organizational safeguards, including access controls, encryption where appropriate, secret management, logging, monitoring, tenant separation, and webhook authentication.</p><p>No internet transmission or storage system can be guaranteed to be completely secure.</p></section>
        <section><h2>9. International transfers</h2><p>Information may be processed in countries other than the country where it was collected. Where required, we use appropriate contractual, technical, and organizational safeguards for international transfers.</p></section>
        <section><h2>10. Your rights</h2><p>Depending on applicable law, you may have rights to:</p><BulletList items={["Access personal information.", "Correct inaccurate information.", "Request deletion.", "Restrict or object to processing.", "Withdraw consent.", "Request data portability.", "Lodge a complaint with a data protection authority."]} /><p>Submit requests to: <a href={`mailto:${visynDetails.email}`}>{visynDetails.email}</a></p><p>We may need to verify your identity before completing a request.</p></section>
        <section><h2>11. Children</h2><p>Visyn is intended for businesses and business users. It is not directed to children, and we do not knowingly collect information directly from children.</p></section>
        <section><h2>12. Changes</h2><p>We may update this Privacy Policy from time to time. We will publish the updated version on this page and change the “Last updated” date.</p></section>
        <section><h2>13. Contact</h2><VisynContactBlock privacy /></section>
        <VisynLegalActions />
      </article>
    </main>
  );
}
